db:
  mysql:
    driver: mysql
    dsn:
    host: localhost
    port: 3306
    username: root
    password: root
    database: witwoywhy
    timeout: 1m
    read_timeout: 1m
    write_timeout: 1m
    max_idle_conns: 1
    max_conns: 5
    max_life_time: 1h
  pg:
    driver: pg
    dsn: postgres://root:root@localhost:5432/witwoywhy
    timeout: 1m
    max_idle_conns: 1
    max_conns: 5
    max_life_time: 1h
